### PR TITLE
Fix a bunch of linter errors

### PR DESCRIPTION
**Pull request by clarfonthey**
I ran the module through autopep8 and made a few manual edits to remove a bunch of linter errors. This makes the module conform to the PEP8 standard a bit more and uses 4-space tabs instead of 2, assuming that that's okay.

### CODE REVIEW

**Comment by msg555** [comment]
It looks like map reading is broken by commenting out several of the read commands which were presumably commented out due to the variable not being used though nonetheless advance the read pointer.  I'm not inclined to risk breaking things for a pull request that makes pervasive and non-critical changes like this on a codebase that has no auto testing framework written.

**Comment by clarfonthey** [comment]
Those comments were definitely not looked-through; I sort of just commented out the not-used lines without thinking. I've removed them from latest commit.

In terms of the rest, I decided to offer them up because I was making an attempt to modify the code so I'd understand it better, although I definitely understand if you'd rather not risk linter changes. They're pretty unintrusive IMO though.

**Comment by msg555** [comment]
Ok thanks, I'll take a closer look tomorrow.  I think I'll probably take most of it but might want to change some of the autopep output.

**Comment by clarfonthey** [comment]
To clarify, I only used autopep8 for the whitespace-related stuff in the first commit. The second commit, I manually changed a few others (e.g. not key in dict => key not in dict) and rearranged a few other things.

Also, the downhill test still passes, so, I'm assuming that this doesn't actually change any functionality minus insignificant performance boosts.

**Comment by clarfonthey** [comment]
This PR is super old so I'm just going to close this.

**Pull request closed without merging**
